### PR TITLE
editor options: allow youtube embed codes (iframe)

### PR DESCRIPTION
**Pull request by markusherzog**
Hi Volmer,

this PR makes it possible to enter youtube embed codes into the editor. We talked about that a couple of month ago (Issue #47).
Took me a while, but here it is :-)

Have a nice day,
Markus

### CODE REVIEW

**Comment by mib32** [comment]
Hi @volmer !
I think that it is not really working. If you go to http://bootsy-demo.herokuapp.com/ and paste  
```
<iframe width="560" height="315" src="//www.youtube.com/embed/d2QdITRRMHg" frameborder="0" allowfullscreen></iframe>
```
line, that i'd taken from `bootsy/spec/features/youtube_support_spec.rb` file - it shows gray screen, because src is being escaped or something...
The same thing is on my server with latest bootsy version.
So i don't know why is test passing, because you can't pass it manually...

I know how to work this around but you need to mess in *wysihtml5.js* file.

**Comment by volmer** [comment]
Hi @mib32 

You can't even test this on the demo app since HTML editing is not enabled in there. I just tested it locally and it works fine.

bootsy

**Comment by markusherzog** [comment]
Can't verify this right now because I'm on the road, but I believe the
reason it's not working is that your src-url is starting with // and
doesn't include the protocol.

**Comment by mib32** [comment]
@volmer hey, thanks for the video, it explains how to do it! i've forgot that you have to use html editing and pasted it directly. sorry for having your time

**Comment by volmer** [comment]
Not a problem :smiley:

**Pull request merged**
