### PR TITLE
Generate JavaScript translations on the fly

### PR DESCRIPTION
**Pull request by driehuis**
This pull request is for a patch that generate JavaScript translations on the fly. This make translating Bootsy easier, which will probably in turn mean fewer questions about Bootsy.

The patch was inspired by Volmer's response to issue #125.

The code Works For Me, and has been tested in English and Dutch.

### CODE REVIEW

**Comment by volmer** [comment]
Hey @driehuis, sorry for the delay. I love the idea and the effort you put on this. We still need to improve this in order to get merged, though. The ruby code needs unit test coverage and the feature as a whole needs acceptance tests too. Please let me know when you want to continue working on this.

**Comment by driehuis** [comment]
Thanks for the feedback. I know that the code itself is just half the work, but wanted to get your feedback before going down the rabbit hole too far. I actually haven't checked to see how it jives with the asset pipeline. I will work on this, time permitting.

**Comment by mib32** [comment]
Maybe a better idea would be to use https://github.com/fnando/i18n-js gem? It takes all translations from your rails locale and makes them available to javascript. We can make this as optional dependency.

**Comment by driehuis** [comment]
That sounds pretty much like the thing I wrote, so if it does the trick, I'm all for it!

**Comment by mib32** [comment]
Yep, it just has tests and reliability and so on.

**Comment by volmer** [comment]
At a first sight it looks a bit overkill to me, but I'm all :+1: to give it a try.

**Comment by volmer** [comment]
Closing this due to inactivity.

**Pull request closed without merging**
