### PR TITLE
Rails.application.config.active_record.belongs_to_required_by_default…

### PR DESCRIPTION
**Pull request by dnswus**
… is set to `true` for new Rails 5 app as mentioned in https://github.com/volmer/bootsy/issues/243.

http://blog.bigbinary.com/2016/02/15/rails-5-makes-belong-to-association-required-by-default.html

### CODE REVIEW

**Comment by volmer** [comment]
The dummy app in `specs/dummy` is working fine without that option. Is there anything missing in it?

**Comment by volmer** [comment]
Perhaps `initiliazers/new_framework_defaults.rb.` ?

**Comment by dnswus** [comment]
@volmer, yes, because the dummy app does not have `initiliazers/new_framework_defaults.rb` and the `Rails.application.config.active_record.belongs_to_required_by_default = true` setting, so it is fine. However, all new Rails 5 app will have that setting set to `true` by default. So I think it would be better to either set the `belongs_to` as `optional: true` or give some guideline in `README.md` to tell people to set `belongs_to_required_by_default` to `false`.

**Comment by volmer** [comment]
> yes, because the dummy app does not have initiliazers/new_framework_defaults.rb and the Rails.application.config.active_record.belongs_to_required_by_default = true setting

So do you mind adding the file to the dummy app then?

**Comment by dnswus** [comment]
@volmer, added.

**Comment by volmer** [comment]
Thanks for contributing!

**Pull request merged**
